import Link from "next/link";

export const metadata = { title: "Terms of Service — Meridian" };

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="text-[16px] font-medium text-ink tracking-tight mb-3">{title}</h2>
      <div className="flex flex-col gap-3 text-[13.5px] text-ink-soft leading-relaxed">{children}</div>
    </section>
  );
}

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-paper">
      <div className="max-w-2xl mx-auto px-8 py-16">
        <Link href="/" className="text-[15px] font-semibold tracking-tight text-ink mb-1 inline-block">
          Meridian
        </Link>
        <h1 className="text-[24px] font-medium text-ink tracking-tight mb-1 mt-3">Terms of Service</h1>
        <p className="text-[12px] text-ink-soft mb-6">Last updated: September 2026</p>

        <div className="bg-amber-soft border border-amber rounded-[4px] px-4 py-3 mb-10 text-[12.5px] text-amber leading-relaxed">
          <strong className="font-medium">Draft, pending legal review.</strong> This document accurately
          describes how Meridian&apos;s software actually works today, but it has not yet been reviewed by
          a lawyer. Treat it as a good-faith description of the service, not a substitute for formal legal
          counsel.
        </div>

        <Section title="1. Acceptance">
          <p>
            By creating an account or using Meridian, you agree to these terms on behalf of yourself and,
            if you register on behalf of a company, that company. Meridian is operated by{" "}
            <strong className="text-ink font-medium">Meridian Techverse Limited</strong>, registered in
            Nigeria.
          </p>
        </Section>

        <Section title="2. What Meridian is">
          <p>
            Meridian is an AI-powered analytics agent: it connects to your databases and documents,
            answers business questions in plain English, and shows its work — the query it ran, data
            quality notes, and a confidence-rated explanation. It is read-only by design: Meridian can
            query and explain, and nothing else. It never writes, alters, or deletes data in any system
            you connect.
          </p>
        </Section>

        <Section title="3. Your account">
          <p>
            You&apos;re responsible for keeping your login credentials secure and for all activity under
            your account. If you invite teammates, you&apos;re responsible for managing their access and
            permissions within your organization&apos;s workspace. We strongly recommend enabling two-factor
            authentication.
          </p>
        </Section>

        <Section title="4. Subscriptions and billing">
          <p>
            Paid plans are billed from the moment you subscribe via Paystack — there is no delayed-billing
            free trial. If you&apos;re not satisfied, you can cancel within 7 days of subscribing for a
            full refund; after that window, cancelling stops future billing but the current billing period
            is not refunded. Plan limits (seats, connected data sources, monthly questions, and monthly
            downloads) are described on our pricing page and enforced automatically.
          </p>
        </Section>

        <Section title="5. Acceptable use">
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 flex flex-col gap-1.5">
            <li>Attempt to bypass, disable, or circumvent Meridian&apos;s read-only enforcement or access controls.</li>
            <li>Use Meridian to process data you are not legally authorized to access or analyze.</li>
            <li>Attempt to gain unauthorized access to another organization&apos;s workspace, data, or account.</li>
            <li>Use the service to build a competing product, or to reverse-engineer the underlying software.</li>
            <li>Use the service for any unlawful purpose.</li>
          </ul>
        </Section>

        <Section title="6. Your data">
          <p>
            You retain ownership of all data you connect to or upload into Meridian. We access it only to
            provide the service to you — running the query you asked for, generating the explanation you
            requested. See our{" "}
            <Link href="/privacy" className="text-teal hover:text-teal-deep transition-colors">
              Privacy Policy
            </Link>{" "}
            for how it&apos;s handled.
          </p>
        </Section>

        <Section title="7. AI-generated content — a real limitation, stated plainly">
          <p>
            Meridian&apos;s explanations are generated by an AI model interpreting deterministically
            computed numbers — the numbers themselves are never invented by the AI, but its interpretation,
            phrasing, and judgment calls can still be wrong. Every answer includes a stated confidence
            level and the underlying query for exactly this reason: verify anything you intend to act on
            for a decision that matters, the same way you&apos;d sanity-check any analyst&apos;s report.
            Meridian does not provide financial, legal, tax, or other professional advice.
          </p>
        </Section>

        <Section title="8. Availability">
          <p>
            We monitor uptime and work to keep the service available, but we do not currently guarantee a
            specific uptime percentage or service-level agreement. Current status and incident history are
            published at{" "}
            <Link href="/status" className="text-teal hover:text-teal-deep transition-colors">
              our status page
            </Link>.
          </p>
        </Section>

        <Section title="9. Limitation of liability">
          <p>
            Meridian is provided &quot;as is.&quot; To the maximum extent permitted by law, Meridian
            Techverse Limited is not liable for indirect, incidental, or consequential damages arising
            from your use of the service, including decisions made based on its output.
          </p>
        </Section>

        <Section title="10. Termination">
          <p>
            You may cancel your subscription and stop using Meridian at any time from your account&apos;s
            Billing page. We may suspend or terminate accounts that violate these terms, including the
            acceptable-use section above.
          </p>
        </Section>

        <Section title="11. Changes to these terms">
          <p>
            If these terms change materially, we&apos;ll update the date at the top of this page and,
            where the change is significant, notify account admins by email.
          </p>
        </Section>

        <Section title="12. Governing law">
          <p>These terms are governed by the laws of the Federal Republic of Nigeria.</p>
        </Section>

        <Section title="13. Contact">
          <p>
            Questions about these terms:{" "}
            <a href="mailto:hello@getmeridiananalytics.com" className="text-teal hover:text-teal-deep transition-colors">
              hello@getmeridiananalytics.com
            </a>
          </p>
        </Section>
      </div>
    </div>
  );
}
