"""
Export (BUILD SPEC section 22). Exports operate on the already-aggregated
result (by_group / preview_rows), never on a fresh unrestricted query - an
export cannot pull more than what the original authorized analysis already
retrieved and passed its output check.

Branding note: CSV is pure tabular data with no metadata capability at
all - a downstream script doing pd.read_csv() on it expects exactly the
columns it asked for, nothing else. Injecting a "Made by Meridian" row or
comment would silently corrupt that for anyone piping the export into
another tool, so CSV carries branding only in its filename, never in its
data. XLSX has real metadata support, so it gets a proper (but still
non-intrusive) treatment: document properties and a print footer, neither
of which touch a single cell of the actual data.
"""
import os
import uuid
import pandas as pd
from app.config import settings


def export_csv(rows: list[dict], base_name: str) -> str:
    os.makedirs(settings.artifacts_dir, exist_ok=True)
    path = os.path.join(settings.artifacts_dir, f"meridian-{base_name}-{uuid.uuid4().hex[:8]}.csv")
    pd.DataFrame(rows).to_csv(path, index=False)
    return path


def export_xlsx(rows: list[dict], base_name: str) -> str:
    os.makedirs(settings.artifacts_dir, exist_ok=True)
    path = os.path.join(settings.artifacts_dir, f"meridian-{base_name}-{uuid.uuid4().hex[:8]}.xlsx")
    with pd.ExcelWriter(path, engine="openpyxl") as writer:
        pd.DataFrame(rows).to_excel(writer, index=False, sheet_name="Data")
        wb = writer.book
        wb.properties.creator = "Meridian"
        wb.properties.last_modified_by = "Meridian"
        wb.properties.title = base_name
        wb.properties.description = "Generated by Meridian - getmeridiananalytics.com"
        ws = writer.sheets["Data"]
        # Only visible when printed/exported to PDF - never touches a cell,
        # so a script reading this file back with pandas/openpyxl sees the
        # exact same data either way.
        ws.oddFooter.center.text = "Made by Meridian"
        ws.oddFooter.right.text = "Page &P of &N"
    return path
