"""
Report Generator (BUILD SPEC sections 24, 25). Builds a management-ready
PDF from a query's already-computed, already-validated result snapshot -
it never re-derives numbers, only lays out what the pipeline already
produced with its evidence and data-quality caveats attached.
"""
import os
import uuid
from fpdf import FPDF
from app.config import settings


_UNICODE_TO_LATIN1 = str.maketrans({
    "\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
    "\u201c": '"', "\u201d": '"', "\u2026": "...",
})


def _safe(text: str) -> str:
    # fpdf2's core fonts are Latin-1; translate common smart punctuation
    # (em dashes, curly quotes) to ASCII equivalents first, then fall back
    # to '?' only for anything genuinely unrepresentable, rather than
    # silently mangling ordinary LLM/UI punctuation.
    return (text or "").translate(_UNICODE_TO_LATIN1).encode("latin-1", "replace").decode("latin-1")


def _mc(pdf: FPDF, h: float, text: str) -> None:
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, h, text)


def generate_report_pdf(title: str, question: str, insight: dict, metrics: dict,
                          by_group: list[dict] | None, data_quality: dict,
                          anomalies: list[dict], sql: str, query_id: str) -> str:
    os.makedirs(settings.artifacts_dir, exist_ok=True)
    path = os.path.join(settings.artifacts_dir, f"report-{uuid.uuid4().hex[:8]}.pdf")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    _mc(pdf, 10, _safe(title))
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(100, 100, 100)
    _mc(pdf, 6, _safe(f"Question: {question}"))
    _mc(pdf, 6, _safe(f"Query ID: {query_id}"))
    pdf.ln(4)
    pdf.set_text_color(0, 0, 0)

    def section(heading: str):
        pdf.set_font("Helvetica", "B", 13)
        pdf.ln(3)
        _mc(pdf, 8, _safe(heading))
        pdf.set_font("Helvetica", "", 11)

    if "error" not in insight:
        section("Executive summary")
        _mc(pdf, 6, _safe(insight.get("what", "")))
        pdf.ln(1)

        section("Where / When")
        _mc(pdf, 6, _safe(f"Where: {insight.get('where', '')}"))
        _mc(pdf, 6, _safe(f"When: {insight.get('when', '')}"))

        section("What contributed")
        _mc(pdf, 6, _safe(insight.get("contributors", "")))

        section("Confidence")
        _mc(pdf, 6, _safe(f"{insight.get('confidence', '')} — {insight.get('confidence_explanation', '')}"))

    if by_group:
        section("Breakdown")
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(100, 7, "Group", border=1)
        pdf.cell(60, 7, "Total", border=1, ln=1)
        pdf.set_font("Helvetica", "", 10)
        for row in by_group[:15]:
            pdf.cell(100, 6, _safe(str(row["group"])), border=1)
            pdf.cell(60, 6, f"{row['total']:,.2f}", border=1, ln=1)

    if anomalies:
        section("Notable findings")
        for a in anomalies[:5]:
            _mc(pdf, 6, _safe(f"- {a['what']} ({a['magnitude']}) [{a['confidence']} confidence]"))

    section("Data quality")
    _mc(pdf, 6, _safe(f"Rows analysed: {data_quality.get('row_count', 0)}"))
    _mc(pdf, 6, _safe(f"Completeness: {data_quality.get('completeness_pct', 100)}%"))
    for note in data_quality.get("notes", []):
        _mc(pdf, 6, _safe(f"- {note}"))

    section("Methodology")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 5, _safe(
        "Generated by an AI analytics agent restricted to read-only, authorized queries. "
        "All figures were computed deterministically (not by the language model); the "
        "model was used only to translate the question into SQL and to interpret the "
        "already-computed results."
    ))
    _mc(pdf, 5, _safe(f"Query: {sql}"))

    section("Data limitations")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 5, _safe(
        "This report reflects only the authorized tables/columns available to the "
        "requesting user and the data quality notes above. Predictive or prescriptive "
        "claims, if any, are explicitly labelled as such and are not guarantees."
    ))

    pdf.output(path)
    return path
